version: '3'

services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - "./:/app"
        working_dir: "/app"

    redis:
        image: "redis:alpine"

    db:
        image: "mysql:8.0"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db
