version: '3'

services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - "./:/app"
        working_dir: "/app"

    redis:
        image: "redis:alpine"
