version: "3"

services:
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - "./:/app"
        working_dir: "/app"

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"

    db:
        image: "mysql:8.0"
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db

    rabbitmq:
        image: "rabbitmq:3.6.6-management"
        ports:
            - "4369:4369"
            - "5672:5672"
            - "15672:15672"
            - "25672:25672"
            - "35197:35197"
